version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: loyalnest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/loyalnest
      JWT_SECRET: supersecret
    ports:
      - "3000:3000"
    depends_on:
      - db  # ne garantit pas la disponibilité, mais on utilise wait-for-postgres.sh

volumes:
  postgres_data:
