name: cagnotte_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"  # updated to support latest Flutter SDK

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3    # latest stable
  flutter_svg: ^2.0.7           # latest stable
  intl: ^0.18.0                 # latest stable
  cupertino_icons: ^1.0.5
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: SF-Pro-Rounded
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Rounded-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Rounded-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Rounded-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Rounded-Bold.otf
          weight: 700
